//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_De_Atencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.cliente_cola = new HashSet<cliente_cola>();
        }
    
        public int cli_id { get; set; }
        public string cli_codigo { get; set; }
        public string cli_nombre { get; set; }
    
        public virtual ICollection<cliente_cola> cliente_cola { get; set; }
    }
}
