//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_De_Atencion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_cola
    {
        public int ccli_id { get; set; }
        public Nullable<int> ccli_cli_id { get; set; }
        public Nullable<int> ccli_col_id { get; set; }
        public Nullable<System.DateTime> ccli_hora_registro { get; set; }
        public Nullable<System.DateTime> ccli_hora_atencion { get; set; }
        public Nullable<System.DateTime> ccli_hora_fin_atencion { get; set; }
        public Nullable<int> ccli_estado_atencion_id { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual cola cola { get; set; }
    }
}
