//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_De_Atencion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ticketContext : DbContext
    {
        public ticketContext()
            : base("name=ticketContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogo> catalogo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_cola> cliente_cola { get; set; }
        public virtual DbSet<cola> cola { get; set; }
    
        public virtual ObjectResult<consultaColaCliente_Result> consultaColaCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultaColaCliente_Result>("consultaColaCliente");
        }
    
        public virtual ObjectResult<consultaColaCliente1_Result> consultaColaCliente1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultaColaCliente1_Result>("consultaColaCliente1");
        }
    
        public virtual ObjectResult<consultaColaCliente2_Result> consultaColaCliente2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultaColaCliente2_Result>("consultaColaCliente2");
        }
    
        public virtual int GuardarClienteCola(string codigo, string nombre)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarClienteCola", codigoParameter, nombreParameter);
        }
    }
}
